config/routes.rb
Gftest::Application.routes.draw do

  root 'trips#index'
  resources :expenses

  resources :members

  resources :trips

  get 'expenses/:id/new' => 'expenses#new_by_id'

  get 'members/:id/new' => 'members#new_by_id'

end

app/models/expense.rb
class Expense < ActiveRecord::Base
  belongs_to :member
end

app/models/member.rb
class Member < ActiveRecord::Base
  has_many :expenses
  belongs_to :trip
end

app/models/trip.rb
class Trip < ActiveRecord::Base
  has_many :members
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/expenses_controller.rb
class ExpensesController < ApplicationController
  before_action :set_expense, only: [:show, :edit, :update, :destroy]

  # GET /expenses
  # GET /expenses.json
  def index
    @expenses = Expense.all
  end

  # GET /expenses/1
  # GET /expenses/1.json
  def show
  end

  # GET /expenses/new
  def new
    @expense = Expense.new
    @member  = (params[:member_id])
  end

  # GET /expenses/1/edit
  def edit
  end

  # POST /expenses
  # POST /expenses.json
  def create
    @expense = Expense.new(expense_params)

    respond_to do |format|
      if @expense.save
        format.html { redirect_to @expense, notice: 'Expense was successfully created.' }
        format.json { render action: 'show', status: :created, location: @expense }
      else
        format.html { render action: 'new' }
        format.json { render json: @expense.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /expenses/1
  # PATCH/PUT /expenses/1.json
  def update
    respond_to do |format|
      if @expense.update(expense_params)
        format.html { redirect_to @expense, notice: 'Expense was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @expense.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /expenses/1
  # DELETE /expenses/1.json
  def destroy
    @expense.destroy
    respond_to do |format|
      format.html { redirect_to expenses_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_expense
      @expense = Expense.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def expense_params
      params.require(:expense).permit(:title, :amount, :comment, :member, :member_id)
    end
end

app/controllers/members_controller.rb
class MembersController < ApplicationController
  before_action :set_member, only: [:show, :edit, :update, :destroy]

  # GET /members
  # GET /members.json
  def index
    @members = Member.all
  end

  # GET /members/1
  # GET /members/1.json
  def show
  end

  # GET /members/new
  def new
    @member = Member.new
  end

  # Get /members/:id/new
  def new_by_id
    @member = Member.new
    @member.trip_id = params[:id]
    render 'new'
  end

  # GET /members/1/edit
  def edit
  end

  # POST /members
  # POST /members.json
  def create
    @member = Member.new(member_params)

    respond_to do |format|
      if @member.save
        format.html { redirect_to @member, notice: 'Member was successfully created.' }
        format.json { render action: 'show', status: :created, location: @member }
      else
        format.html { render action: 'new' }
        format.json { render json: @member.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /members/1
  # PATCH/PUT /members/1.json
  def update
    respond_to do |format|
      if @member.update(member_params)
        format.html { redirect_to @member, notice: 'Member was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @member.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /members/1
  # DELETE /members/1.json
  def destroy
    @member.destroy
    respond_to do |format|
      format.html { redirect_to members_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_member
      @member = Member.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def member_params
      params.require(:member).permit(:name, :trip_id)
    end
end

app/controllers/trips_controller.rb
class TripsController < ApplicationController
  before_action :set_trip, only: [:show, :edit, :update, :destroy]

  # GET /trips
  # GET /trips.json
  def index
    @trips = Trip.all
  end

  # GET /trips/1
  # GET /trips/1.json
  def show
    @mockuserid = 1
  end

  # GET /trips/new
  def new
    @trip = Trip.new
  end

  # GET /trips/1/edit
  def edit
  end

  # POST /trips
  # POST /trips.json
  def create
    @trip = Trip.new(trip_params)

    respond_to do |format|
      if @trip.save
        format.html { redirect_to @trip, notice: 'Trip was successfully created.' }
        format.json { render action: 'show', status: :created, location: @trip }
      else
        format.html { render action: 'new' }
        format.json { render json: @trip.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /trips/1
  # PATCH/PUT /trips/1.json
  def update
    respond_to do |format|
      if @trip.update(trip_params)
        format.html { redirect_to @trip, notice: 'Trip was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @trip.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /trips/1
  # DELETE /trips/1.json
  def destroy
    @trip.destroy
    respond_to do |format|
      format.html { redirect_to trips_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_trip
      @trip = Trip.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def trip_params
      params.require(:trip).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/expenses_helper.rb
module ExpensesHelper
end

app/helpers/members_helper.rb
module MembersHelper
end

app/helpers/trip_helper.rb
module TripHelper
end

app/helpers/trips_helper.rb
module TripsHelper
end

app/views/expenses/_form.html.haml
= form_for @expense do |f|
  - if @expense.errors.any?
    #error_explanation
      %h2= "#{pluralize(@expense.errors.count, "error")} prohibited this expense from being saved:"
      %ul
        - @expense.errors.full_messages.each do |msg|
          %li= msg



  .field
    = f.label :amount
    = f.text_field :amount
  .field
    = f.label :comment
    = f.text_area :comment
  .field
    = f.label :member_id
    // = f.hidden_field :member_id
    = f.text_area :member_id
  .actions
    = f.submit 'Save'

app/views/expenses/edit.html.haml
%h1 Editing expense

= render 'form'

= link_to 'Show', @expense
\|
= link_to 'Back', expenses_path

app/views/expenses/index.html.haml
%h1 Listing expenses

%table
  %tr
    %th Amount
    %th Comment
    %th Member
    %th
    %th
    %th

  - @expenses.each do |expense|
    %tr
      %td= expense.amount
      %td= expense.comment
      %td= expense.member_id
      %td= link_to 'Show', expense
      %td= link_to 'Edit', edit_expense_path(expense)
      %td= link_to 'Destroy', expense, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Expense', new_expense_path

app/views/expenses/new.html.haml
%h1 New expense

= render 'form'

= link_to 'Back', expenses_path

app/views/expenses/show.html.haml
%p#notice= notice

%p
  %b Amount:
  = @expense.amount
%p
  %b Comment:
  = @expense.comment
%p
  %b Member:
  = @expense.member_id

= link_to 'Edit', edit_expense_path(@expense)
\|
= link_to 'Back', expenses_path

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Welcom to groupfood</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= yield %>

</body>
</html>

app/views/members/_form.html.haml
= form_for @member do |f|
  - if @member.errors.any?
    #error_explanation
      %h2= "#{pluralize(@member.errors.count, "error")} prohibited this member from being saved:"
      %ul
        - @member.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :trip_id
    = f.number_field :trip_id
  .actions
    = f.submit 'Save'

app/views/members/edit.html.haml
%h1 Editing member

= render 'form'

= link_to 'Show', @member
\|
= link_to 'Back', members_path

app/views/members/index.html.haml
%h1 Listing members

%table
  %tr
    %th Name
    %th Trip
    %th
    %th
    %th

  - @members.each do |member|
    %tr
      %td= member.name
      %td= member.trip_id
      %td= link_to 'Show', member
      %td= link_to 'Edit', edit_member_path(member)
      %td= link_to 'Destroy', member, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Member', new_member_path

app/views/members/new.html.haml
%h1 New member

= render 'form'

= link_to 'Back', members_path

app/views/members/show.html.haml
%p#notice= notice
%p
  %b Name:
  = @member.name
%p
  %b Expenses:
  - @member.expenses.each do |expense|
    = expense.title
    ($#{expense.amount})

= link_to "Add Expense", new_expense_path
= link_to 'Edit', edit_member_path(@member)
= link_to 'Back', members_path

app/views/trip/add_expense.html.erb
<h1>Trip#add_expense</h1>
<p>Find me in app/views/trip/add_expense.html.erb</p>

app/views/trip/add_person.html.erb
<h1>Trip#add_person</h1>
<p>Find me in app/views/trip/add_person.html.erb</p>

app/views/trips/_form.html.haml
= form_for @trip do |f|
  - if @trip.errors.any?
    #error_explanation
      %h2= "#{pluralize(@trip.errors.count, "error")} prohibited this trip from being saved:"
      %ul
        - @trip.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .actions
    = f.submit 'Save'

app/views/trips/edit.html.haml
%h1 Editing trip

= render 'form'

= link_to 'Show', @trip
\|
= link_to 'Back', trips_path

app/views/trips/index.html.haml
%h1 Welcome to groupfood. 

%h2 Select a trip.
%table
  %tr
    %th Trip Name
  - @trips.each do |trip|
    %tr
      %td= link_to trip.name, trip
      
%h3=link_to 'Create a new trip', new_trip_path

app/views/trips/new.html.haml
%h1 Create your new trip

= render 'form'

= link_to 'Back', trips_path

app/views/trips/show.html.haml
%p#notice= notice

%h1= @trip.name
- if @trip.members.length == 0
  %table{:border => "1"}
    %tbody
      %tr
        %th Name
        %th Total Expenses 
      %tr
        - if @trip.members.length == 0
          - @trip.members.each do |m|
            %td= link_to m.name, edit_member_path(@trip)
            %td $99.00
    %tr
- else
  %p Find some friends for this trip!
%br
%br

%table
  %tbody
    %tr
      %th Total Trip Expenses
      %th Expense amount per person
    %tr
      %td TODO:99.99
      %td TODO: 5.00 per person
= link_to 'Change name of this trip', edit_trip_path(@trip)
\|
= link_to 'Back To List of Trips', trips_path
%br
%br
= link_to 'Add a member to this trip.', controller: 'members', action: 'new_by_id', id: @trip.id 